// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STAJ1.Data;

#nullable disable

namespace STAJ1.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260731073436_SonOkuma")]
    partial class SonOkuma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("STAJ1.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adsoyad");

                    b.Property<bool>("CevrimiciMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eposta");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sifrehash");

                    b.Property<DateTime?>("SonGorulme")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("kullanicilar");
                });

            modelBuilder.Entity("STAJ1.Models.Kullanicilog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ipadresi");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer")
                        .HasColumnName("kullaniciid");

                    b.Property<DateTime>("islemTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tarih");

                    b.Property<string>("islemTipi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("islemtipi");

                    b.HasKey("Id");

                    b.ToTable("kullaniciloglari");
                });

            modelBuilder.Entity("STAJ1.Models.Kullanicirol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer")
                        .HasColumnName("kullaniciid");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rolid");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("RolId");

                    b.ToTable("kullanicirol");
                });

            modelBuilder.Entity("STAJ1.Models.Mesaj", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("text")
                        .HasColumnName("DosyaYolu");

                    b.Property<int>("gonderenid")
                        .HasColumnType("integer")
                        .HasColumnName("gonderenkullaniciid");

                    b.Property<DateTime>("gondermeTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gonderilmetarihi");

                    b.Property<string>("icerik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icerik");

                    b.Property<bool>("okundumu")
                        .HasColumnType("boolean")
                        .HasColumnName("okundumu");

                    b.Property<int>("sohbetid")
                        .HasColumnType("integer")
                        .HasColumnName("sohbetid");

                    b.HasKey("id");

                    b.ToTable("mesajlar");
                });

            modelBuilder.Entity("STAJ1.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roladi");

                    b.HasKey("Id");

                    b.ToTable("rol");
                });

            modelBuilder.Entity("STAJ1.Models.Sohbet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("grupadi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupadi");

                    b.Property<bool>("grupmu")
                        .HasColumnType("boolean")
                        .HasColumnName("grupmu");

                    b.Property<DateTime>("olusturmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturulmatarihi");

                    b.HasKey("id");

                    b.ToTable("sohbetler");
                });

            modelBuilder.Entity("STAJ1.Models.SohbetKatilimci", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("SonOkumaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sonokumatarihi");

                    b.Property<DateTime>("katilmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("katilmatarihi");

                    b.Property<int>("kullaniciid")
                        .HasColumnType("integer")
                        .HasColumnName("kullaniciid");

                    b.Property<int>("sohbetid")
                        .HasColumnType("integer")
                        .HasColumnName("sohbetid");

                    b.HasKey("id");

                    b.ToTable("sohbetkatilimcilari");
                });

            modelBuilder.Entity("STAJ1.Models.Kullanicirol", b =>
                {
                    b.HasOne("STAJ1.Models.Kullanici", "Kullanici")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STAJ1.Models.Rol", "Rol")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("STAJ1.Models.Kullanici", b =>
                {
                    b.Navigation("KullaniciRolleri");
                });

            modelBuilder.Entity("STAJ1.Models.Rol", b =>
                {
                    b.Navigation("KullaniciRolleri");
                });
#pragma warning restore 612, 618
        }
    }
}
